spring.application.name=back-inmind-latam

spring.datasource.url=jdbc:mysql://qainminddb-instance-1.c7ia4m266sw5.us-east-2.rds.amazonaws.com:3306/InMindDB
spring.datasource.username=dbuser_qa_Andres
spring.datasource.password=andres123
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.devtools.restart.enabled=false

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
